version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/core.txt" }}
      - run:
          name: run-requirements-setup
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/core.txt && pip install -r requirements/addtional.txt
      - run:
          name: run-flake8
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: run-tests
          command: |
            ./run_tests
      - store_artifacts:
          path: test-reports/
          destination: python_app
